spring.application.name=book-swap-lending-platform

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-red-mode-am9j7pog-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_k2ichtwb0vsl

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

# Mail (keep for later)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@example.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5